{% set name = "sdgym" %}
{% set version = "0.11.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sdgym-{{ version }}.tar.gz
  sha256: c9368e0a54e120fc02f2e3090a0ac7bbf15888d0c8221d02eaa6d1a782501329

build:
  entry_points:
    - sdgym=sdgym.__main__:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pytest-runner >=2.11.1
    - pip
    - setuptools
  run:
    - python >={{ python_min }},<3.14
    - anyio
    - appdirs >=1.3
    - boto3 >=1.28,<2
    - botocore >=1.31,<2
    - cloudpickle >=2.1.0
    - compress-pickle >=1.2.0
    - humanfriendly >=10.0
    - numpy >=1.22.2,<2
    - openpyxl >=3.1.2
    - pandas >=1.4.0
    - psutil >=5.7
    - scikit-learn >=1.0.2
    - scipy >=1.7.3
    - tabulate >=0.8.3,<0.9
    - pytorch >=2.6.0
    - tqdm >=4.66.3
    - xlsxwriter >=1.2.8
    - rdt >=1.17.0
    - sdmetrics >=0.20.1
    - sdv >=1.21.0

test:
  imports:
    - sdgym
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/sdv-dev/SDGym
  summary: Benchmark tabular synthetic data generators using a variety of datasets
  license: BUSL-1.1
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/sdv
