{% set name = "sdgym" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sdgym-{{ version }}.tar.gz
  sha256: e05735354136ebf13f327375867eb5cd15fa082f7a728ca99352b297282cd8b8

build:
  entry_points:
    - sdgym=sdgym.__main__:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - python
    - pytest-runner >=2.11.1
    - pip
  run:
    - python >=3.7,<3.11
    - anyio
    - appdirs >=1.3,<2
    - boto3 >=1.15.0,<2
    - botocore >=1.18,<2
    - compress-pickle >=1.2.0,<3
    - humanfriendly >=8.2,<11
    - numpy >=1.20.0,<2
    - pandas >=1.1.3,<2
    - psutil >=5.7,<6
    - scikit-learn >=0.24,<2
    - scipy >=1.5.4,<2
    - tabulate >=0.8.3,<0.9
    - pytorch >=1.8.0,<3
    - tqdm >=4.15,<5
    - xlsxwriter >=1.2.8,<4
    - rdt >=1.3.0,<2.0
    - sdmetrics >=0.9.1,<1.0
    - sdv >=1.0.0,<2.0

test:
  imports:
    - sdgym
  requires:
    - pip

about:
  home: https://github.com/sdv-dev/SDGym
  summary: Benchmark tabular synthetic data generators using a variety of datasets
  license: BUSL-1.1
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/sdv
