{% set name = "sdgym" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sdgym-{{ version }}.tar.gz
  sha256: b31d3e5aed57dc2aaa1cf282d3b1ba85b1a5d40c07250c90b5cfb4d3e7ddf9b9

build:
  entry_points:
    - sdgym=sdgym.__main__:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - python
    - pytest-runner >=2.11.1
    - pip
  run:
    - python >=3.8,<3.13
    - anyio
    - appdirs >=1.3,<2
    - boto3 >=1.28,<2
    - botocore >=1.31,<2
    - compress-pickle >=1.2.0,<3
    - humanfriendly >=8.2,<11
    - numpy >=1.21.0,<2
    - pandas >=1.4.0,<2
    - psutil >=5.7,<6
    - scikit-learn >=1.0.2,<2
    - scipy >=1.7.3,<2
    - tabulate >=0.8.3,<0.9
    - pytorch >=1.9.0,<3
    - tqdm >=4.29,<5
    - xlsxwriter >=1.2.8,<4
    - rdt >=1.12.1,<2.0
    - sdmetrics >=0.14.1,<1.0
    - sdv >=1.13.1,<2.0

test:
  imports:
    - sdgym
  requires:
    - pip

about:
  home: https://github.com/sdv-dev/SDGym
  summary: Benchmark tabular synthetic data generators using a variety of datasets
  license: BUSL-1.1
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/sdv
