{% set name = "sdgym" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sdgym-{{ version }}.tar.gz
  sha256: 2245fdb0a5f6f769d82903e76871d1598fe92333cedcf656181ea85e5a5e6e8b

build:
  entry_points:
    - sdgym=sdgym.__main__:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pytest-runner >=2.11.1
    - pip
  run:
    - python >={{ python_min }},<3.13
    - anyio
    - appdirs >=1.3
    - boto3 >=1.28,<2
    - botocore >=1.31,<2
    - cloudpickle >=2.1.0
    - compress-pickle >=1.2.0
    - humanfriendly >=8.2
    - numpy >=1.21.0,<2
    - pandas >=1.4.0
    - psutil >=5.7
    - scikit-learn >=1.0.2
    - scipy >=1.7.3
    - tabulate >=0.8.3,<0.9
    - pytorch >=1.9.0
    - tqdm >=4.29
    - xlsxwriter >=1.2.8
    - rdt >=1.12.1
    - sdmetrics >=0.14.1
    - sdv >=1.13.1

test:
  imports:
    - sdgym
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/sdv-dev/SDGym
  summary: Benchmark tabular synthetic data generators using a variety of datasets
  license: BUSL-1.1
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/sdv
